[package]
name = "rust_8bit"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_8bit"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module"] }
image = "0.24.7"